#!/bin/bash
set -e

AUTHORIZED_KEYS=/root/.ssh/authorized_keys

if [[ -e "$AUTHORIZED_KEYS" ]] && grep -q kbarrett@dev "$AUTHORIZED_KEYS"; then
	echo "kbarrett@dev key has already been added to $AUTHORIZED_KEYS."
else
	DIR=`dirname "$AUTHORIZED_KEYS"`
	echo "Creating directory $DIR..."
	mkdir -p "$DIR"
	chmod 700 "$DIR"
	chown root:root "$DIR"
	echo "Editing $AUTHORIZED_KEYS..."
	cat /etc/kbarrett_key.pub >> "$AUTHORIZED_KEYS"
	echo "Success: kbarrett@dev key has been added to $AUTHORIZED_KEYS"
	:<<BEGIN
	cat <<-EOF

		+------------------------------------------------------------------------------+
		| Insecure SSH key installed                                                   |
		|                                                                              |
		| DO NOT expose port 22 on the Internet unless you know what you are doing!    |
		|                                                                              |
		| Use the private key below to connect with user root                         |
		+------------------------------------------------------------------------------+

	EOF
BEGIN
	#cat /etc/insecure_key
	#echo -e "\n\n"
fi
